bundle_size = {
    'Redflesh Fish': 10,
    'Fresh Mushroom': 10,
    'Shy Wild Flower': 10,
    'Heavy Iron Ore': 10,
    'Natural Pearl': 10,
    'Exquisite Mushroom': 10,
    'Tough Leather': 10,
    'Treated Meat': 10,
    'Bright Wild Flower': 10,
    'Oreha Solar Carp': 10,
    'Oreha Relic': 10,
    'Tender Timber': 10,
    'Excavating Crystal': 10,
    'Crude Mushroom': 100,
    'Rare Relic': 10,
    'Caldarr Solar Carp': 10,
    'Caldarr Relic': 10,
    'Strong Iron Ore': 10,
    'Iron Ore': 100,
    'Hunting Crystal': 10,
    'Caldarr Thick Raw Meat': 10,
    'Caldarr Thick Meat': 10,
    'Oreha Thick Meat': 10,
    'Sturdy Timber': 10,
    'Fishing Crystal': 10,
    'Thick Raw Meat': 100,
    'Wild Flower': 100,
    'Timber': 100,
    'Ancient Relic': 100,
    'Fish': 100,
}
