engravings_names = [
    'Disrespect',
    'Spirit Absorption',
    'Ether Enhancement',
    'Grudge',
    'Super Charge',
    'Strong Will',
    'Drops of Ether',
    'Crisis Evasion',
    'Keen Blunt Weapon',
    'Vital Point Strike',
    'Increased Max MP',
    'MP Regen',
    'Master of Escape',
    'Fortitude',
    'Crushing Fist',
    'Shield Piercing',
    "Masters's Tenacity",
    'Divine Protection',
    'Heavy Armor',
    'Explosive Expert',
    'Enhanced Shield',
    'Necromancy',
    'Preemptive Strike',
    'Broken Bone',
    'Lightning Fury',
    'Cursed Doll',
    'Contender',
    'Master of Ambush',
    'Magick Stream',
    'Barricade',
    'Raid Captain',
    'Awakening',
    'Master Brawler',
    'Mass Increase',
    'Propulsion',
    'Hit Master',
    'Adrenaline',
    'All-out Attack',
    'Expert',
    'Emergency Rescue',
    'Precision Dagger',
    'Atk. Power Reduction',
    'Atk. Speed Reduction',
    'Defense Reduction',
    'Move Speed Reduction',
    'Mayhem',
    "Berserker's Technique",
    'Enhanced Weapon',
    'Pistoleer',
    'Esoteric Skill Enhancement',
    'First Intention',
    'Ultimate Skill: Taijutsu',
    'Shock Training',
    'Barrage',
    'Firepower Enhancement',
    'True Courage',
    'Desperate Salvation',
    'Reflux',
    'Igniter',
    'Esoteric Flurry',
    'Deathblow',
    'Time to Hunt',
    'Peacemaker',
    'Blessed Aura',
    'Judgment',
    'Demonic Impulse',
    'Perfect Suppression',
    'Surge',
    'Remaining Energy',
    'Death Strike',
    'Loyal Companion',
    'Energy Overflow',
    'Robust Spirit',
    'Lone Knight',
    'Combat Readiness',
    'Rage Hammer'
]
